In [2]:
# Import libraries

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import time
import numpy as np
import os
import os.path

In [9]:
pip install Faker unicodecsv

Collecting Faker
  Downloading Faker-13.13.0-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.3 MB/s eta 0:00:01
Requirement already satisfied: unicodecsv in /home/mike/anaconda3/envs/sf/lib/python3.8/site-packages (0.14.1)
Requirement already satisfied: python-dateutil>=2.4 in /home/mike/anaconda3/envs/sf/lib/python3.8/site-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/mike/anaconda3/envs/sf/lib/python3.8/site-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Installing collected packages: Faker
Successfully installed Faker-13.13.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
data = pd.read_csv("/home/mike/Documents/Coding/Data/WI Club Night - Pivot table.csv")
display(data.head(3))

,Event Date,Topic,Attended,User Name (Original Name),First Name,Last Name,Email,City,Country/Region,State/Province,Phone,Registration Time,Approval Status,Join Time,Leave Time,Time in Session (minutes),Is Guest,Country/Region Name,Source Name
0,"Apr 05, 2022",Renewable Energy,Yes,Dhan .,Dhan,.,junglenutcracker@gmail.com,NaN,SG,Other,NaN,"Apr 05, 2022 09:55:55",approved,"Apr 05, 2022 17:48:39","Apr 05, 2022 19:21:03",93,Yes,Singapore,Email
1,"Apr 05, 2022",Renewable Energy,Yes,Joseph Bampton,Joseph,Bampton,bamptonj01@icloud.com,NaN,AU,NaN,NaN,"Apr 04, 2022 13:54:02",approved,"Apr 05, 2022 18:02:11","Apr 05, 2022 18:09:37",8,Yes,Australia,NaN
2,"Apr 05, 2022",Renewable Energy,Yes,Sophie Bayar,Sophie,Bayar,sophie.bayars@gmail.com,Sydney,AU,NSW,451468778,"Apr 04, 2022 15:07:34",approved,"Apr 05, 2022 17:29:05","Apr 05, 2022 18:05:27",37,Yes,Australia,Email

In [7]:
display(data.shape)

(492, 19)

# Anonimiser

In [60]:
from faker import Faker
fake = Faker()

def a_First_Name(row):
    new_First_Name = fake.first_name()
    return new_First_Name
data['First Name'] = data.apply(a_First_Name, axis=1)

def a_Last_Name(row):
    new_Last_Name = fake.last_name()
    return new_Last_Name
data['Last Name'] = data.apply(a_Last_Name, axis=1)

# take a quick look
data.head()

,Event Date,Topic,Attended,User Name (Original Name),First Name,Last Name,Email,City,Country/Region,State/Province,Phone,Registration Time,Approval Status,Join Time,Leave Time,Time in Session (minutes),Is Guest,Country/Region Name,Source Name
0,"Apr 05, 2022",Renewable Energy,Yes,Dhan .,Connie,Dodson,junglenutcracker@gmail.com,NaN,SG,Other,NaN,"Apr 05, 2022 09:55:55",approved,"Apr 05, 2022 17:48:39","Apr 05, 2022 19:21:03",93,Yes,Singapore,Email
1,"Apr 05, 2022",Renewable Energy,Yes,Joseph Bampton,Ricardo,Miller,bamptonj01@icloud.com,NaN,AU,NaN,NaN,"Apr 04, 2022 13:54:02",approved,"Apr 05, 2022 18:02:11","Apr 05, 2022 18:09:37",8,Yes,Australia,NaN
2,"Apr 05, 2022",Renewable Energy,Yes,Sophie Bayar,Laurie,Mcmahon,sophie.bayars@gmail.com,Sydney,AU,NSW,451468778,"Apr 04, 2022 15:07:34",approved,"Apr 05, 2022 17:29:05","Apr 05, 2022 18:05:27",37,Yes,Australia,Email
3,"Apr 05, 2022",Renewable Energy,Yes,Marc Bernard,Taylor,Colon,marc.a.bernard@gmail.com,ST IVES,US,NaN,404879132,"Apr 03, 2022 11:21:49",approved,"Apr 05, 2022 17:33:49","Apr 05, 2022 19:21:03",108,Yes,United States,NaN
4,"Apr 05, 2022",Renewable Energy,Yes,Peter Broggian,Jenny,Pierce,peter@apparelcorp.com.au,NaN,GB,Other,NaN,"Apr 05, 2022 17:22:39",approved,"Apr 05, 2022 17:22:51","Apr 05, 2022 17:57:58",36,Yes,United Kingdom,Personal from Steve

In [51]:
"""
This script will Anonymize the data in original_data.csv file to Anonymized form in anonymized_data csv file
"""

import unicodecsv as csv
from faker import Faker
from collections import defaultdict


def anonymize():
    'Anonymizes the given original data to anonymized form'
    # Load the faker and its providers
    faker  = Faker()

    # Create mappings of names &amp; emails to faked names &amp; emails.
    names = defaultdict(faker.name)
    first_names = defaultdict(faker.first_name)
    last_names = defaultdict(faker.last_name)
    emails = defaultdict(faker.email)

    with open("WI Club Night - Pivot table.csv", 'rU') as f:
        with open("WI Club Night - Pivot table - anonymized.csv", 'wb') as o :
            # Use the DictReader to easily extract fields
            reader = csv.DictReader(f)
            writer = csv.DictWriter(o, reader.fieldnames)
            writer.writeheader()
            for row in reader:
                row['User Name (Original Name)'] = names[row['User Name (Original Name)']]
                row['First Name'] = first_names[row['First Name']]
                row['Last Name'] = last_names[row['Last Name']]
                row['Email'] = emails[row['Email']]
                writer.writerow(row)

if __name__ == '__main__':
    anonymize()

/tmp/ipykernel_174351/291096400.py:21: DeprecationWarning: 'U' mode is deprecated
  with open("WI Club Night - Pivot table.csv", 'rU') as f:

AttributeError: 'str' object has no attribute 'decode'

In [49]:
anonim_data = data.apply(anonymize)

NameError: name 'apply' is not defined

In [53]:
import unicodecsv as csv
from faker import Faker
from collections import defaultdict

def anonymize_rows(rows):
    """
    Rows is an iterable of dictionaries that contain name and
    email fields that need to be anonymized.
    """
    # Load the faker and its providers
    faker  = Faker.create()

    # Create mappings of names & emails to faked names & emails.
    names  = defaultdict(faker.name)
    first_names = defaultdict(faker.first_name)
    last_names = defaultdict(faker.last_name)
    emails = defaultdict(faker.email)

    # Iterate over the rows and yield anonymized rows.
    for row in rows:
        # Replace the name and email fields with faked fields.
        row['User Name (Original Name)']  = names[row['User Name (Original Name)']]
        row['First Name']  = first_names[row['First Name']]
        row['Last Name']  = last_names[row['Last Name']]
        row['Email'] = emails[row['Email']]

        # Yield the row back to the caller
        yield row


def anonymize(source, target):
    """
    The source argument is a path to a CSV file containing data to anonymize,
    while target is a path to write the anonymized CSV data to.
    """
    
    source = "/home/mike/Documents/Coding/Data/WI Club Night - Pivot table.csv"
    target = "/home/mike/Documents/Coding/Data/WI Club Night - Pivot table - anonimised.csv"

    with open(source, 'rU') as f:
        with open(target, 'w') as o:
            # Use the DictReader to easily extract fields
            reader = csv.DictReader(f)
            writer = csv.DictWriter(o, reader.fieldnames)

            # Read and anonymize data, writing to target file.
            for row in anonymize_rows(reader):
                writer.writerow(row)

if __name__ == '__main__':
    anonymize_rows(data)

In [41]:
anonim_data = data.apply(anonymize_rows, axis=1)

# anonymize_rows(data)

In [54]:
data

,Event Date,Topic,Attended,User Name (Original Name),First Name,Last Name,Email,City,Country/Region,State/Province,Phone,Registration Time,Approval Status,Join Time,Leave Time,Time in Session (minutes),Is Guest,Country/Region Name,Source Name
0,"Apr 05, 2022",Renewable Energy,Yes,Dhan .,Dhan,.,junglenutcracker@gmail.com,NaN,SG,Other,NaN,"Apr 05, 2022 09:55:55",approved,"Apr 05, 2022 17:48:39","Apr 05, 2022 19:21:03",93,Yes,Singapore,Email
1,"Apr 05, 2022",Renewable Energy,Yes,Joseph Bampton,Joseph,Bampton,bamptonj01@icloud.com,NaN,AU,NaN,NaN,"Apr 04, 2022 13:54:02",approved,"Apr 05, 2022 18:02:11","Apr 05, 2022 18:09:37",8,Yes,Australia,NaN
2,"Apr 05, 2022",Renewable Energy,Yes,Sophie Bayar,Sophie,Bayar,sophie.bayars@gmail.com,Sydney,AU,NSW,451468778,"Apr 04, 2022 15:07:34",approved,"Apr 05, 2022 17:29:05","Apr 05, 2022 18:05:27",37,Yes,Australia,Email
3,"Apr 05, 2022",Renewable Energy,Yes,Marc Bernard,Marc,Bernard,marc.a.bernard@gmail.com,ST IVES,US,NaN,404879132,"Apr 03, 2022 11:21:49",approved,"Apr 05, 2022 17:33:49","Apr 05, 2022 19:21:03",108,Yes,United States,NaN
4,"Apr 05, 2022",Renewable Energy,Yes,Peter Broggian,Peter,Broggian,peter@apparelcorp.com.au,NaN,GB,Other,NaN,"Apr 05, 2022 17:22:39",approved,"Apr 05, 2022 17:22:51","Apr 05, 2022 17:57:58",36,Yes,United Kingdom,Personal from Steve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,"May 31, 2022",ASX,No,Leila,Leila,Liu,tzbbyl@gmail.com,NaN,AU,NaN,NaN,"May 30, 2022 13:20:46",approved,--,--,--,--,Australia,Email
488,"May 31, 2022",ASX,No,David,David,Vas,vasdavid2000@yahoo.com.sg,NaN,US,NaN,NaN,"May 29, 2022 14:08:23",approved,--,--,--,--,United States,Email
489,"May 31, 2022",ASX,No,Weina,Weina,Zhu,weina.zhu@blockchaineconomyllc.com,Dallas,US,NaN,'+61452316632,"May 30, 2022 17:02:38",approved,--,--,--,--,United States,Email
490,"May 31, 2022",ASX,No,Bec,Bec,R,yren8742@gmail.com,NaN,AU,NaN,NaN,"May 29, 2022 15:07:16",approved,--,--,--,--,Australia,Email
491,"May 31, 2022",ASX,No,Zack,Zack,Louw,zack@funden.app,NaN,GB,Other,NaN,"May 25, 2022 20:49:42",approved,--,--,--,--,United Kingdom,WI Investor Club - Website